---
- name: Deploy local openshift cluster
  command: oc cluster up --insecure-skip-tls-verify=true
  become: yes

- name: Create zuul user .kube directory
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory

- name: Setup zuul user kube config
  copy:
    src: /root/.kube/config
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    mode: 0600
    remote_src: yes
  become: yes

- name: Login as system:admin
  command: oc login -u system:admin

- name: Who am i
  command: oc whoami -c
